### ISSUE TITLE
SkyScanner API Error Handling

### ISSUE THREAD

**Issue by ctrachte** [ctrachte/SimpliFly#20]
Handle all responses from API, including 404, 500, etc.

The application must fail gracefully, eg. nothing hard-broken, warning message, redirects etc. 
- Upon request fail, attempt to load data from cache instead using service worker.

**Comment by MrRedBeard** [comment]
Seeing 

SkyScanner.js:28 GET https://skyscanner-skyscanner-flight-search-v1.p.rapidapi.com/apiservices/browsedates/v1.0/US/USD/en-US/ZUN-sky/BLI-sky/2021-01-05?inboundpartialdate=2021-01-05 400 (Bad Request)

Location Zuni, New Mexico

**Comment by ctrachte** [comment]
Yes, currently our version of skyscanner (free) seems to only accept USA airport locations. We need to have this in the error handling.

**Comment by MrRedBeard** [comment]
@ctrachte lol New Mexico is in the US

**Comment by ctrachte** [comment]
Oh, I read that as "Mexico" my bad. We can create an issue card for this. I haven't gotten far into my next task.
