### ISSUE TITLE
Weather response XML error

### ISSUE THREAD

**Issue by ctrachte** [ctrachte/SimpliFly#23]
Upon clicking "Find Flights":

WeatherStack.js:48 Uncaught TypeError: Cannot read property 'getElementsByTagName' of undefined
    at XMLHttpRequest.<anonymous> (WeatherStack.js:48)

This happens I believe when a piece of the response data is missing from the XML returned by the API.

**Comment by MrRedBeard** [comment]
You can assign this to me if you want

**Comment by ctrachte** [comment]
Ok will switch it now.

**Comment by MrRedBeard** [comment]
Do you know what location you used to get this?

**Comment by ctrachte** [comment]
Not exactly, but I'm pretty sure it was a handful of the smaller Airports/cities

**Comment by MrRedBeard** [comment]
I keep trying random ones and haven't seen it.... yet

**Comment by MrRedBeard** [comment]
Got it on Harrisburg, Pennsylvania

Uncaught TypeError: Cannot read property 'getElementsByTagName' of undefined
    at XMLHttpRequest.<anonymous> (WeatherStack.js:17)

A point forecast is unavailable for the requested location
https://forecast.weather.gov/MapClick.php?lat=47.1715&lon=8.51622&unit=0&lg=english&FcstType=dwml
