### ISSUE TITLE
Create flight listings from Skyscanner Data

### ISSUE THREAD

**Issue by ctrachte** [ctrachte/SimpliFly#3]
Loop through array of flights returned, and create a new listing in the UI  for each flight.

- when no flights, have a placeholder
- when loading flights, have a 'loading' component showing

**Comment by ashleighchun** [comment]
Id like to give this a try:)

**Comment by ctrachte** [comment]
Sure! Be sure to checkout the Skyscanner API https://rapidapi.com/skyscanner/api/skyscanner-flight-search?endpoint=5aa1edd5e4b06ec3937b23f0 to make sure you are using the correct data to populate the UI components.

Please create a new JS file in the `helpers` folder to write your methods in.

Caleb
